services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tooket
      POSTGRES_PASSWORD: tooket
      POSTGRES_DB: tooket_ther
    ports:
      - "5432:5432"
    volumes:
      - tooket_pgdata:/var/lib/postgresql/data

volumes:
  tooket_pgdata:
