/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}", 
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d3e4fe",
        "secondary": "#006a61",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline-variant": "#c6c6cd",
        "primary": "#000000",
        "error-container": "#ffdad6",
        "surface-container-low": "#eff4ff",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#86f2e4",
        "on-tertiary-container": "#7073ff",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "tertiary": "#000000",
        "on-primary-container": "#7c839b",
        "on-tertiary-fixed": "#07006c",
        "primary-fixed-dim": "#bec6e0",
        "tertiary-fixed": "#e1e0ff",
        "tertiary-fixed-dim": "#c0c1ff",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-high": "#dce9ff",
        "on-primary-fixed": "#131b2e",
        "background": "#f8f9ff",
        "on-error": "#ffffff",
        "primary-container": "#131b2e",
        "secondary-fixed": "#89f5e7",
        "inverse-on-surface": "#eaf1ff",
        "inverse-surface": "#213145",
        "on-secondary-fixed": "#00201d",
        "surface-container": "#e5eeff",
        "on-surface": "#0b1c30",
        "on-secondary-container": "#006f66",
        "error": "#ba1a1a",
        "surface-dim": "#cbdbf5",
        "tertiary-container": "#07006c",
        "outline": "#76777d",
        "secondary-fixed-dim": "#6bd8cb",
        "on-surface-variant": "#45464d",
        "surface-tint": "#565e74",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005049",
        "inverse-primary": "#bec6e0",
        "on-background": "#0b1c30",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "4px",
        "card-padding": "20px",
        "section-gap": "32px",
        "container-padding": "24px",
        "gutter": "16px"
      },
      fontFamily: {
        'display': ['"Inter"', 'sans-serif'],
        'body-md': ['"Inter"', 'sans-serif'],
        'label-sm': ['"Work Sans"', 'sans-serif'],
        'data-mono': ['"Work Sans"', 'sans-serif'],
        'headline-md': ['"Inter"', 'sans-serif'],
        'body-lg': ['"Inter"', 'sans-serif']
      },
      fontSize: {
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "display-xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "data-mono": ["14px", {"lineHeight": "20px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}