"""describe change

Revision ID: 6e36bd730954
Revises: 003_poster_lineup
Create Date: 2026-04-06 05:29:35.389729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e36bd730954'
down_revision: Union[str, Sequence[str], None] = '003_poster_lineup'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id_created_at'), table_name='bookings')
    op.create_index('ix_bookings_user_id_created_at', 'bookings', ['user_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.drop_index(op.f('ix_queue_entries_concert_dequeue'), table_name='queue_entries')
    op.create_index('ix_queue_entries_concert_dequeue', 'queue_entries', ['concert_id', 'status', 'priority_score', 'entered_at'], unique=False, postgresql_ops={'priority_score': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_queue_entries_concert_dequeue', table_name='queue_entries', postgresql_ops={'priority_score': 'DESC'})
    op.create_index(op.f('ix_queue_entries_concert_dequeue'), 'queue_entries', ['concert_id', 'status', sa.literal_column('priority_score DESC'), 'entered_at'], unique=False)
    op.drop_index('ix_bookings_user_id_created_at', table_name='bookings', postgresql_ops={'created_at': 'DESC'})
    op.create_index(op.f('ix_bookings_user_id_created_at'), 'bookings', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
